### ISSUE TITLE
Number.prototype.toFixed, toPrecision and toExponential

### ISSUE THREAD

**Issue by kika** [purescript/purescript-globals#12]
There's an abandoned module at https://github.com/Jonplussed/purescript-number-format
@paf31 advised implementing this in globals instead.
PR #11

**Comment by sharkdp** [comment]
If you are interested in a PureScript version of this, there is https://github.com/sharkdp/purescript-format which provides at least some of the functionality you seem to be interested in.

**Comment by sharkdp** [comment]
I believe this can be closed, since #11 has been merged.

**Comment by garyb** [comment]
👍
