### ISSUE TITLE
Should the properly typed stringify live here?

### ISSUE THREAD

**Issue by justinwoo** [purescript/purescript-globals#15]
Brought this up the other day, but it would be good (for me, at least, when using and teaching Purescript) to have the properly typed `stringify` in here: https://twitter.com/paf31/status/884984889942167553

I think some concerns revolve around whether or not we should export the class at all (I don't know how this would work with newtypes), etc.

**Comment by paf31** [comment]
The problem is that constructing the dictionaries makes this possibly quite inefficient.

**Comment by safareli** [comment]
@paf31 when class definition is empty can we optimize it to not result in constructing dictionaries?

(if there is issue for it can you link please)

**Comment by garyb** [comment]
purescript/purescript#2768

**Comment by garyb** [comment]
I guess we can close this now it's in prelude :smile:

**Comment by garyb** [comment]
It’s the show instance for records.

**Comment by safareli** [comment]
Ah it's in [compiler/0.12](https://github.com/purescript/purescript-prelude/blob/compiler/0.12/src/Data/Show.purs) branch
